import React from 'react';

export const metadata = {
    title: 'About  ||  My first Next App',
    description: 'Generated by create next app',
  }

const AboutPage = () => {
    return (
        <div>
            AboutPage
        </div>
    );
};

export default AboutPage;