import React from 'react';
export const metadata = {
    title: 'Add-cart || Dashboard || My first Next App',
    description: 'Generated by create next app',
  }
const AddPage = () => {
    return (
        <div>
            AddPage
        </div>
    );
};

export default AddPage;