import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My first Next App',
  description: 'Generated by create next app',
}

const  RootLayout = ({ children }) =>{
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav><a href="">Home</a>
        </nav> */}
        
        {children}
        {/* <footer>Footer</footer> */}
      </body>
    
    </html>
  )
}
export default RootLayout;