import React from 'react';


export const metadata = {
    title: 'Dashboard || My first Next App',
    description: 'Generated by create next app',
  }
const DashboardPage = () => {
    return (
        <div>
            <div>dashboard</div>
        </div>
    );
};

export default DashboardPage;